#!/bin/bash

GREEN='\033[0;32m'
RED="\033[0;31m"
NC='\033[0m' # No Color

project="dpad"

remove_project () {
    rm -rf $HOME/$project
}

create_project () {
    echo -e "Creating new ${GREEN}$HOME/$project${NC}..." &&
    dart create "$HOME/$project" > /dev/null
}

remove_bin_and_tests () {
    rm -rf $HOME/$project/bin
    rm -rf $HOME/$project/test
}

open_project () {
    echo -e "Opening in ${GREEN}VS Code${NC}..." &&
    code -n $HOME/$project &&
    code -a $HOME/$project/lib/$project.dart
}

check_if_exists () {
    if [ -d "$HOME/$project" ]; then
        echo -e "${GREEN}$project${NC} directory already exists. Removing ${RED}$HOME/$project${NC}..." &&
        remove_project
    fi
}

check_if_exists
create_project
remove_bin_and_tests
open_project