#!/bin/bash

GREEN='\033[0;32m'
RED="\033[0;31m"
NC='\033[0m' # No Color

project="dpad"


echo -e "Creating new ${GREEN}$HOME/$project${NC}..." &&

remove_project () {
    rm -rf $HOME/$project
}

create_project () {
    echo -e "Creating new ${GREEN}$HOME/$project${NC}..." &&
    dart create "$HOME/$project" > /dev/null &&
}

open_project () {
    # echo -e "Running ${GREEN}$project${NC}..." &&
    # dart run $HOME/$project/bin/$project.dart &&
    echo -e "Opening in ${GREEN}VS Code${NC}..." &&
    code -n $HOME/$project &&
    code -a $HOME/$project/lib/$project.dart $HOME/$project/bin/$project.dart
}

check_if_exists () {
    if [ -d "$HOME/$project" ]; then
        echo -e "${GREEN}$project${NC} directory already exists. Removing ${RED}$HOME/$project${NC}..." &&
        remove_project
    fi
}

check_if_exists
create_project
open_project