#!/bin/bash

GREEN='\033[0;32m'
RED="\033[0;31m"
NC='\033[0m' # No Color

if [ "$#" -eq 2 ];
    then
        _directory=$1
        _command=$2
        echo -e "Running ${GREEN}${_command}${NC} in ${GREEN}${_directory}${NC}"
        find $_directory -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && $_command" \;
    else
        echo -e "${RED}usage: $0 <path> <command>${NC}"
fi


